<?xml version="1.0" encoding = "UTF-8" standalone = "yes"?>
<?xml-stylesheet type = "text/xsl" href = "pets.xsl"?>

<!DOCTYPE petshop [
        <!ELEMENT  petshop (pet)>
        <!ELEMENT  pet (id, name, age, race, temperament, category, gender, birthDate,
        length, price, pedigri, height, details, pictureURL)>
        <!ELEMENT  id (#PCDATA)>
        <!ELEMENT  name (#PCDATA)>
        <!ELEMENT  age (#PCDATA)>
        <!ELEMENT  race (#PCDATA)>
        <!ELEMENT  type	(#PCDATA)>
        <!ELEMENT  temperament (type*)>
        <!ELEMENT  category (#PCDATA)>
        <!ELEMENT  gender (#PCDATA)>
        <!ELEMENT  birthDate (#PCDATA)>
        <!ELEMENT  length (#PCDATA)>
        <!ELEMENT  price (#PCDATA)>
        <!ELEMENT  pedigri (#PCDATA)>
        <!ELEMENT  height (#PCDATA)>
        <!ELEMENT  details (#PCDATA)>
        <!ELEMENT  pictureURL (#PCDATA)>
        ]>

<petshop>
    <pet>
        <id>1</id>
        <name>Tonny</name>
        <age>2</age>
        <race>Beagle</race>
        <temperament>
            <type>Nicenicenicenicenicencine</type>
            <type>Welcoming</type>
        </temperament>
        <category>Dog</category>
        <gender>Male</gender>
        <birthDate>12/12/2016</birthDate>
        <length>60</length>
        <price>120</price>
        <pedigri>Yes</pedigri>
        <height>40</height>
        <details>Is really nice</details>
        <pictureURL>www.google.com</pictureURL>
    </pet>
</petshop>
